config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  devise_for :users
  root 'pages#home'

  get 'contact', to: 'pages#contact'

  get 'about', to: 'pages#about'

  get 'privacy', to: 'pages#privacy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  validates :name, :email, :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end


  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    respond_to do |format|
      if @enquiry.save
        EnquiryMailer.response(@enquiry.id).deliver_now
        EnquiryMailer.received(@enquiry.id).deliver_now
        format.html { redirect_to root_path, notice: 'Your enquiry has been sent.' }
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :phone, :subject, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def contact
    @enquiry = Enquiry.new
  end

  def about
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-4">
    <%= f.input :name, label: false, placeholder: 'Your name' %>
  </div>
    <div class="col-md-4">
    <%= f.input :email, label: false, placeholder: 'Your email' %>
  </div>
  <div class="col-md-4">
    <%= f.input :phone, label: false, placeholder: 'Your phone' %>
  </div>
</div>
    <%= f.input :subject, label: false, collection: ['General enquiry', 'Website error', 'Membership query'], prompt: 'Choose reason for enquiry' %>
    <%= f.input :message, label: false, placeholder: "Enter your message", input_html: { rows: 5 } %>
  </div>

  <div class="form-actions">
    <button type="submit" name="button" class="btn btn-primary">
      <i class="fa fa-paper-place"></i> Send message
    </button>
  </div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.name %></td>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.phone %></td>
        <td><%= enquiry.subject %></td>
        <td><%= enquiry.message %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @enquiry.phone %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @enquiry.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  <a class="navbar-brand" href="/">My fancy app</a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link <%= 'active' if current_page?(root_path) %>" href="/">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link <%= 'active' if current_page?(about_path) %>" href="#">About</a>
    </li>
    <li class="nav-item">
      <a class="nav-link <%= 'active' if current_page?(contact_path) %>" href="/contact">Contact</a>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to '<i class="fa fa-sign-out-alt"></i>Sign out'.html_safe, destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to '<i class="fa fa-user-plus"></i>Register'.html_safe, new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '<i class="fa fa-sign-in-alt"></i>Sign in'.html_safe, new_user_session_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:title) ? yield(:title) : 'Your Default title here' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
          <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title, "About" %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% content_for :title, "Contact" %>
<h1>Contact Us</h1>
<div class="row">
  <div class="col-md-6">
    <h2>We'd love to hear from you!</h2>
    <div class="card card-body">
      <%= render 'enquiries/form' %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :title, "Home" %>
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/pages/privacy.html.erb
<% content_for :title, "Privacy policy" %>
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>